In [1]:
import numpy as np
import pandas as pd

## Pivot Tables

In [24]:
data={
    "Date":pd.date_range("2026-01-01",periods=20),
    "Product":["A","B","C","D"]*5,
    "Region":["East","West","North","South"]*5,
    "Sales":np.random.randint(100,1000,20),
    "Units":np.random.randint(10,100,20),
    "Rep":["John","Jane","Jim","Jill"]*5
}
df=pd.DataFrame(data)

df["Month"]=df["Date"].dt.month_name()
df["Quarter"]="Q" + df["Date"].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units   Rep    Month Quarter
0  2026-01-01       A   East    331     16  John  January      Q1
1  2026-01-02       B   West    385     11  Jane  January      Q1
2  2026-01-03       C  North    184     78   Jim  January      Q1
3  2026-01-04       D  South    679     20  Jill  January      Q1
4  2026-01-05       A   East    513     73  John  January      Q1
5  2026-01-06       B   West    476     63  Jane  January      Q1
6  2026-01-07       C  North    830     70   Jim  January      Q1
7  2026-01-08       D  South    480     69  Jill  January      Q1
8  2026-01-09       A   East    631     21  John  January      Q1
9  2026-01-10       B   West    537     80  Jane  January      Q1
10 2026-01-11       C  North    399     30   Jim  January      Q1
11 2026-01-12       D  South    833     12  Jill  January      Q1
12 2026-01-13       A   East    759     23  John  January      Q1
13 2026-01-14       B   West    862     83  Jane  January      Q1
14 2026-01-15       C  North    809     25   Jim  January      Q1
15 2026-01-16       D  South    155     62  Jill  January      Q1
16 2026-01-17       A   East    560     89  John  January      Q1
17 2026-01-18       B   West    330     96  Jane  January      Q1
18 2026-01-19       C  North    186     82   Jim  January      Q1
19 2026-01-20       D  South    748     68  Jill  January      Q1

In [26]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc="median")

Product      A      B      C      D
Region
East     560.0    NaN    NaN    NaN
North      NaN    NaN  399.0    NaN
South      NaN    NaN    NaN  679.0
West       NaN  476.0    NaN    NaN

In [28]:
pivot2=pd.pivot_table(df,values=["Sales","Units"],index="Region",columns="Product",aggfunc="median")
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     560.0    NaN    NaN    NaN  23.0   NaN   NaN   NaN
North      NaN    NaN  399.0    NaN   NaN   NaN  70.0   NaN
South      NaN    NaN    NaN  679.0   NaN   NaN   NaN  62.0
West       NaN  476.0    NaN    NaN   NaN  80.0   NaN   NaN

## Cross Tabs

In [29]:
pd.crosstab(df["Region"],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0